{% set name = "lcov_cobertura" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lcov_cobertura-{{ version }}.tar.gz
  sha256: efa8e264f2bddebb7f5024e4ace12b633d9d59048bc647427d1e1b9688c8b58f

build:
  entry_points:
    - lcov_cobertura = lcov_cobertura.lcov_cobertura:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - lcov_cobertura.lcov_cobertura
  commands:
    - pip check
    - lcov_cobertura --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://eriwen.github.io/lcov-to-cobertura-xml/
  summary: LCOV to Cobertura XML converter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
